# Generated by Django 3.2.13 on 2023-06-03 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
